# Dependabot configuration for NNGC MicroServices
# Automated dependency updates for security and maintenance

version: 2
updates:
  # Root project Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "bisho"  # Replace with your GitHub username
    assignees:
      - "bisho"  # Replace with your GitHub username
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "java"
      - "maven"
    target-branch: "bishop_dev"  # Target development branch first
    
  # API Gateway service
  - package-ecosystem: "maven"
    directory: "/api-gateway"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 3
    reviewers:
      - "bisho"
    commit-message:
      prefix: "deps(api-gateway)"
    labels:
      - "dependencies"
      - "api-gateway"
      - "java"
    target-branch: "bishop_dev"
    
  # Customer Service
  - package-ecosystem: "maven"
    directory: "/customer-service"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "bisho"
    commit-message:
      prefix: "deps(customer-service)"
    labels:
      - "dependencies"
      - "customer-service"
      - "java"
    target-branch: "bishop_dev"
    
  # Registration Service
  - package-ecosystem: "maven"
    directory: "/registration-service"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "bisho"
    commit-message:
      prefix: "deps(registration-service)"
    labels:
      - "dependencies"
      - "registration-service" 
      - "java"
    target-branch: "bishop_dev"
    
  # Token Service
  - package-ecosystem: "maven"
    directory: "/token-service"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:30"
    open-pull-requests-limit: 3
    reviewers:
      - "bisho"
    commit-message:
      prefix: "deps(token-service)"
    labels:
      - "dependencies"
      - "token-service"
      - "java"
    target-branch: "bishop_dev"
    
  # Email Service
  - package-ecosystem: "maven"
    directory: "/email-service"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "bisho"
    commit-message:
      prefix: "deps(email-service)"
    labels:
      - "dependencies"
      - "email-service"
      - "java"
    target-branch: "bishop_dev"
    
  # Google Service
  - package-ecosystem: "maven"
    directory: "/google-service"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "bisho"
    commit-message:
      prefix: "deps(google-service)"
    labels:
      - "dependencies"
      - "google-service"
      - "java"
    target-branch: "bishop_dev"
    
  # Stripe Service
  - package-ecosystem: "maven"
    directory: "/stripe-service"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:30"
    open-pull-requests-limit: 3
    reviewers:
      - "bisho"
    commit-message:
      prefix: "deps(stripe-service)"
    labels:
      - "dependencies"
      - "stripe-service"
      - "java"
    target-branch: "bishop_dev"
    
  # Service Registry
  - package-ecosystem: "maven"
    directory: "/service-registry"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "bisho"
    commit-message:
      prefix: "deps(service-registry)"
    labels:
      - "dependencies"
      - "service-registry"
      - "java"
    target-branch: "bishop_dev"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "bisho"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    target-branch: "bishop_dev"

  # Docker base image updates
  - package-ecosystem: "docker"
    directory: "/api-gateway"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "bisho"
    commit-message:
      prefix: "docker(api-gateway)"
    labels:
      - "dependencies"
      - "docker"
      - "api-gateway"
    target-branch: "bishop_dev"
    
  - package-ecosystem: "docker"
    directory: "/customer-service"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "bisho"
    commit-message:
      prefix: "docker(customer-service)"
    labels:
      - "dependencies"
      - "docker"
      - "customer-service"
    target-branch: "bishop_dev"

# Security-focused dependency updates
# Dependabot will automatically create PRs for:
# - Security vulnerabilities (immediately)
# - Major version updates (weekly)
# - Minor/patch updates (weekly)
# - Docker base image updates (monthly)
# - GitHub Actions updates (monthly)

# Pull requests will be automatically:
# - Assigned to you for review
# - Labeled appropriately
# - Targeted to development branch first
# - Limited to prevent PR spam