server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Customer Service Routes
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - StripPrefix=1

        # Token Service Routes
        - id: token-service
          uri: lb://token-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # Stripe Service Routes
        - id: stripe-service
          uri: lb://stripe-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1

        # Email Service Routes
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
          filters:
            - StripPrefix=1

        # Google Service Routes
        - id: google-service
          uri: lb://google-service
          predicates:
            - Path=/api/google/**
          filters:
            - StripPrefix=1
# Spring Config
  config:
   activate:
      on-profile: docker

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

